MySQL_host: LocalHost
MySQL_port: 3306
MySQL_database: LiveWeather
MySQL_username: newuser1
MySQL_password: xxxx
MySQL_weatherpreferences: WeatherPreferences
timerInterval: 5
apiKey: 
resourcePack: 
defaultResourcePack:
